<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE Films [
    <!ELEMENT Films (Film*)>
        <!ELEMENT Film (Title, Time?, Status, Vote, RunTime, Certification, Budget, Tag, Genres, Directors, Actors)>
            <!ATTLIST Film Id CDATA #REQUIRED>
            <!ATTLIST Film PosterPath CDATA #REQUIRED>

        <!ELEMENT Title (#PCDATA)>
            <!ATTLIST Title OriginalTitle CDATA #REQUIRED>
            
        <!ELEMENT Time EMPTY>
            <!ATTLIST Time Day CDATA #REQUIRED>
            <!ATTLIST Time Month CDATA #REQUIRED>
            <!ATTLIST Time Year CDATA #REQUIRED>

        <!ELEMENT Status (#PCDATA)>
        <!ELEMENT Vote (#PCDATA)>
            <!ATTLIST Vote Count CDATA #REQUIRED>
            
        <!ELEMENT RunTime (#PCDATA)>
        <!ELEMENT Certification (#PCDATA)>
        <!ELEMENT Budget (#PCDATA)>
        <!ELEMENT Tag (#PCDATA)>
        <!ELEMENT Genres (Genre*)>
            <!ELEMENT Genre EMPTY>
                <!ATTLIST Genre Id CDATA #REQUIRED>
                <!ATTLIST Genre Label CDATA #REQUIRED>
        <!ELEMENT Directors (Director*)>
            <!ELEMENT Director EMPTY>
                <!ATTLIST Director Id CDATA #REQUIRED>
                <!ATTLIST Director Name CDATA #REQUIRED>
        <!ELEMENT Actors (Actor*)>
            <!ELEMENT Actor EMPTY>
                <!ATTLIST Actor Id CDATA #REQUIRED>
                <!ATTLIST Actor ActName CDATA #REQUIRED>
                <!ATTLIST Actor CharName CDATA #REQUIRED>
]>

<Films>
	<Film Id="2" PosterPath="/gZCJZOn4l0Zj5hAxsMbxoS6CL0u.jpg" >
		<Title OriginalTitle="Ariel" >Ariel</Title>
		<Time Day="21" Month="10" Year="1988"/>
		<Status>Released</Status>
		<Vote Count="61">6.9</Vote>
		<RunTime>72</RunTime>
		<Certification></Certification>
		<Budget></Budget>
		<Tag></Tag>
		<Genres>
			<Genre Id="18" Label="Drama"/>
			<Genre Id="80" Label="Crime"/>
		</Genres>
		<Directors>
			<Director Id="16767" Name="Aki Kaurismäki"/>
		</Directors>
		<Actors>
			<Actor Id="54768" ActName="Turo Pajala" CharName="Taisto Olavi Kasurinen"/>
			<Actor Id="54769" ActName="Susanna Haavisto" CharName="Irmeli Katariina Pihlaja"/>
			<Actor Id="4826" ActName="Matti Pellonpää" CharName="Mikkonen"/>
			<Actor Id="54770" ActName="Eetu Hilkamo" CharName="Riku"/>
		</Actors>
	</Film>
	<Film Id="3" PosterPath="/lfaiYUVL7vPE57xgTscJN3kN5P1.jpg" >
		<Title OriginalTitle="Varjoja paratiisissa" >Shadows in Paradise</Title>
		<Time Day="16" Month="10" Year="1986"/>
		<Status>Released</Status>
		<Vote Count="46">7.3</Vote>
		<RunTime>74</RunTime>
		<Certification></Certification>
		<Budget></Budget>
		<Tag></Tag>
		<Genres>
			<Genre Id="18" Label="Drama"/>
			<Genre Id="35" Label="Comedy"/>
		</Genres>
		<Directors>
			<Director Id="16767" Name="Aki Kaurismäki"/>
		</Directors>
		<Actors>
			<Actor Id="4826" ActName="Matti Pellonpää" CharName="Nikander"/>
			<Actor Id="5999" ActName="Kati Outinen" CharName="Ilona Rajamäki"/>
			<Actor Id="4828" ActName="Sakari Kuosmanen" CharName="Melartin"/>
			<Actor Id="53508" ActName="Esko Nikkari" CharName="Co-worker"/>
			<Actor Id="1086499" ActName="Kylli Köngäs" CharName="Ilona's Girlfriend"/>
			<Actor Id="222320" ActName="Pekka Laiho" CharName="Shop Steward"/>
			<Actor Id="1086500" ActName="Jukka-Pekka Palo" CharName="Third Man"/>
		</Actors>
	</Film>
	<Film Id="5" PosterPath="/eQs5hh9rxrk1m4xHsIz1w11Ngqb.jpg" >
		<Title OriginalTitle="Four Rooms" >Four Rooms</Title>
		<Time Day="9" Month="12" Year="1995"/>
		<Status>Released</Status>
		<Vote Count="873">6.4</Vote>
		<RunTime>98</RunTime>
		<Certification>R</Certification>
		<Budget>4e+06</Budget>
		<Tag>Twelve outrageous guests. Four scandalous requests. And one lone bellhop, in his first day on the job, who's in for the wildest New year's Eve of his life.</Tag>
		<Genres>
			<Genre Id="80" Label="Crime"/>
			<Genre Id="35" Label="Comedy"/>
		</Genres>
		<Directors>
			<Director Id="3110" Name="Allison Anders"/>
			<Director Id="3111" Name="Alexandre Rockwell"/>
			<Director Id="2294" Name="Robert Rodriguez"/>
			<Director Id="138" Name="Quentin Tarantino"/>
		</Directors>
		<Actors>
			<Actor Id="3129" ActName="Tim Roth" CharName="Ted the Bellhop"/>
			<Actor Id="3131" ActName="Antonio Banderas" CharName="Man"/>
			<Actor Id="3130" ActName="Jennifer Beals" CharName="Angela"/>
			<Actor Id="3125" ActName="Madonna" CharName="Elspeth"/>
			<Actor Id="3141" ActName="Marisa Tomei" CharName="Margaret"/>
			<Actor Id="62" ActName="Bruce Willis" CharName="Leo"/>
			<Actor Id="138" ActName="Quentin Tarantino" CharName="Chester Rush"/>
			<Actor Id="3122" ActName="Sammi Davis" CharName="Jezebel"/>
			<Actor Id="3123" ActName="Amanda de Cadenet" CharName="Diana"/>
			<Actor Id="3124" ActName="Valeria Golino" CharName="Athena"/>
			<Actor Id="3127" ActName="Lili Taylor" CharName="Raven"/>
			<Actor Id="2545" ActName="Lawrence Bender" CharName="Long Hair Yuppy Scum"/>
			<Actor Id="3126" ActName="Ione Skye" CharName="Eva"/>
			<Actor Id="3128" ActName="Alicia Witt" CharName="Kiva"/>
			<Actor Id="2555" ActName="David Proval" CharName="Siegfried"/>
			<Actor Id="3132" ActName="Lana McKissack" CharName="Sarah"/>
			<Actor Id="3134" ActName="Tamlyn Tomita" CharName="Wife"/>
			<Actor Id="3138" ActName="Kathy Griffin" CharName="Betty"/>
			<Actor Id="3137" ActName="Paul Calderon" CharName="Norman"/>
			<Actor Id="3136" ActName="Salma Hayek" CharName="TV Dancing Girl"/>
			<Actor Id="3133" ActName="Patricia Vonne" CharName="Corpse"/>
			<Actor Id="3135" ActName="Danny Verduzco" CharName="Juancho"/>
			<Actor Id="37336" ActName="Kimberly Blair" CharName="Hooker"/>
			<Actor Id="3140" ActName="Marc Lawrence" CharName="Sam the Bellhop"/>
		</Actors>
	</Film>
	<Film Id="6" PosterPath="/lNXmgUrP6h1nD53gkFh4WDzT6RZ.jpg" >
		<Title OriginalTitle="Judgment Night" >Judgment Night</Title>
		<Time Day="15" Month="10" Year="1993"/>
		<Status>Released</Status>
		<Vote Count="100">6.5</Vote>
		<RunTime>110</RunTime>
		<Certification>R</Certification>
		<Budget>21</Budget>
		<Tag>Don't move. Don't whisper. Don't even breathe.</Tag>
		<Genres>
			<Genre Id="28" Label="Action"/>
			<Genre Id="53" Label="Thriller"/>
			<Genre Id="80" Label="Crime"/>
		</Genres>
		<Directors>
			<Director Id="2042" Name="Stephen Hopkins"/>
		</Directors>
		<Actors>
			<Actor Id="2880" ActName="Emilio Estevez" CharName="Frank Wyatt"/>
			<Actor Id="9777" ActName="Cuba Gooding Jr." CharName="Mike Peterson"/>
			<Actor Id="5724" ActName="Denis Leary" CharName="Fallon"/>
			<Actor Id="12799" ActName="Jeremy Piven" CharName="Ray Cochran"/>
			<Actor Id="11803" ActName="Peter Greene" CharName="Sykes"/>
			<Actor Id="52422" ActName="Michael DeLorenzo" CharName="Teddy, the Kid"/>
			<Actor Id="121667" ActName="Everlast" CharName="Rhodes"/>
			<Actor Id="102710" ActName="Michael Wiseman" CharName="Travis"/>
			<Actor Id="1077264" ActName="Relioues Webb" CharName="Dre"/>
			<Actor Id="154124" ActName="Eugene Williams" CharName="Buck"/>
			<Actor Id="55964" ActName="Christine Harnos" CharName="Linda Wyatt"/>
			<Actor Id="105988" ActName="Galyn Görg" CharName="Clarissa"/>
			<Actor Id="22621" ActName="Angela Alvarado" CharName="Rita"/>
			<Actor Id="10822" ActName="Stephen Dorff" CharName="John Wyatt"/>
			<Actor Id="1226696" ActName="Will Zahrn" CharName="Charley"/>
		</Actors>
	</Film>
	<Film Id="8" PosterPath="/8YyIjOAxwzD3fZMdmJrfiApod4l.jpg" >
		<Title OriginalTitle="Life in Loops (A Megacities RMX)" >Life in Loops (A Megacities RMX)</Title>
		<Time Day="1" Month="1" Year="2006"/>
		<Status>Released</Status>
		<Vote Count="5">6.8</Vote>
		<RunTime>80</RunTime>
		<Certification></Certification>
		<Budget>42000</Budget>
		<Tag>A Megacities remix.</Tag>
		<Genres>
			<Genre Id="99" Label="Documentary"/>
		</Genres>
		<Directors>
			<Director Id="34833" Name="Timo Novotny"/>
		</Directors>
		<Actors>
		</Actors>
	</Film>
	<Film Id="9" PosterPath="" >
		<Title OriginalTitle="Sonntag im August" >Sunday in August</Title>
		<Time Day="2" Month="9" Year="2004"/>
		<Status>Released</Status>
		<Vote Count="2">5.3</Vote>
		<RunTime>15</RunTime>
		<Certification></Certification>
		<Budget></Budget>
		<Tag></Tag>
		<Genres>
			<Genre Id="18" Label="Drama"/>
		</Genres>
		<Directors>
			<Director Id="867" Name="Marc Meyer"/>
			<Director Id="914" Name="Anna Haas"/>
		</Directors>
		<Actors>
			<Actor Id="901" ActName="Rita Lengyel" CharName="Alexandra"/>
			<Actor Id="902" ActName="Milton Welsh" CharName="Er"/>
		</Actors>
	</Film>
	<Film Id="11" PosterPath="/btTdmkgIvOi0FFip1sPuZI2oQG6.jpg" >
		<Title OriginalTitle="Star Wars" >Star Wars</Title>
		<Time Day="25" Month="5" Year="1977"/>
		<Status>Released</Status>
		<Vote Count="9624">8.2</Vote>
		<RunTime>121</RunTime>
		<Certification>PG</Certification>
		<Budget>1.1e+07</Budget>
		<Tag>A long time ago in a galaxy far, far away...</Tag>
		<Genres>
			<Genre Id="12" Label="Adventure"/>
			<Genre Id="28" Label="Action"/>
			<Genre Id="878" Label="Science Fiction"/>
		</Genres>
		<Directors>
			<Director Id="1" Name="George Lucas"/>
		</Directors>
		<Actors>
			<Actor Id="2" ActName="Mark Hamill" CharName="Luke Skywalker"/>
			<Actor Id="3" ActName="Harrison Ford" CharName="Han Solo"/>
			<Actor Id="4" ActName="Carrie Fisher" CharName="Princess Leia Organa"/>
			<Actor Id="24343" ActName="Peter Mayhew" CharName="Chewbacca"/>
			<Actor Id="6" ActName="Anthony Daniels" CharName="See Threepio (C-3PO)"/>
			<Actor Id="24342" ActName="David Prowse" CharName="Darth Vader (performer)"/>
			<Actor Id="15152" ActName="James Earl Jones" CharName="Darth Vader (voice)"/>
			<Actor Id="5" ActName="Peter Cushing" CharName="Grand Moff Tarkin"/>
			<Actor Id="12248" ActName="Alec Guinness" CharName="Ben &#39;Obi-Wan&#39; Kenobi"/>
			<Actor Id="33032" ActName="Phil Brown" CharName="Uncle Owen"/>
			<Actor Id="131625" ActName="Shelagh Fraser" CharName="Aunt Beru"/>
			<Actor Id="130" ActName="Kenny Baker" CharName="Artoo-Detoo (R2-D2)"/>
			<Actor Id="132538" ActName="Jack Purvis" CharName="Chief Jawa"/>
			<Actor Id="69249" ActName="Eddie Byrne" CharName="General Willard"/>
			<Actor Id="42570" ActName="Don Henderson" CharName="General Taggi"/>
			<Actor Id="216087" ActName="Alex McCrindle" CharName="General Dodonna"/>
			<Actor Id="12829" ActName="Richard LeParmentier" CharName="General Motti"/>
			<Actor Id="47401" ActName="Drewe Henley" CharName="Red Leader"/>
			<Actor Id="47698" ActName="Denis Lawson" CharName="Red Two (Wedge Antilles)"/>
			<Actor Id="17356" ActName="Garrick Hagon" CharName="Red Three (Biggs)"/>
			<Actor Id="162432" ActName="Jack Klaff" CharName="Red Four (John &#39;D&#39;)"/>
			<Actor Id="663" ActName="William Hootkins" CharName="Red Six (Porkins)"/>
			<Actor Id="79489" ActName="Leslie Schofield" CharName="Commander #1"/>
			<Actor Id="1729623" ActName="Michael Leader" CharName="Stormtrooper"/>
			<Actor Id="58475" ActName="Angus MacInnes" CharName="Gold Leader"/>
			<Actor Id="151819" ActName="Jeremy Sinden" CharName="Gold Two"/>
			<Actor Id="202276" ActName="Graham Ashley" CharName="Gold Five"/>
			<Actor Id="1216947" ActName="David Ankrum" CharName="Red Two, Wedge Antilles (voice) (uncredited)"/>
			<Actor Id="1271058" ActName="Mark Austin" CharName="Boba Fett (special edition) (uncredited)"/>
			<Actor Id="3044" ActName="Scott Beach" CharName="Stormtrooper (voice) (uncredited)"/>
			<Actor Id="1271059" ActName="Lightning Bear" CharName="Stormtrooper (uncredited)"/>
			<Actor Id="1271060" ActName="Jon Berg" CharName="Cantina Alien (uncredited)"/>
			<Actor Id="1271061" ActName="Doug Beswick" CharName="Cantina Alien (uncredited)"/>
			<Actor Id="199356" ActName="Paul Blake" CharName="Greedo (uncredited)"/>
			<Actor Id="1271062" ActName="Janice Burchette" CharName="Nabrun Leids (uncredited)"/>
			<Actor Id="1271063" ActName="Ted Burnett" CharName="Wuher (uncredited)"/>
			<Actor Id="1271064" ActName="John Chapman" CharName="Drifter (Red 12) (uncredited)"/>
			<Actor Id="1271065" ActName="Gilda Cohen" CharName="Cantina Patron (uncredited)"/>
			<Actor Id="1178140" ActName="Tim Condren" CharName="Stormtrooper (uncredited)"/>
			<Actor Id="186229" ActName="Barry Copping" CharName="Wioslea (uncredited)"/>
			<Actor Id="1271066" ActName="Alfie Curtis" CharName="Dr. Evazan (uncredited)"/>
			<Actor Id="1271067" ActName="Robert Davies" CharName="Cantina Patron (uncredited)"/>
			<Actor Id="104149" ActName="Maria De Aragon" CharName="Greedo (uncredited)"/>
			<Actor Id="1271068" ActName="Robert A. Denham" CharName="Hrchek Kal Fas (uncredited)"/>
			<Actor Id="1271069" ActName="Frazer Diamond" CharName="Jawa (uncredited)"/>
			<Actor Id="53587" ActName="Peter Diamond" CharName="Stormtrooper / Tusken Raider / Death Star Trooper / Garouf Lafoe (uncredited)"/>
			<Actor Id="1271070" ActName="Warwick Diamond" CharName="Jawa (uncredited)"/>
			<Actor Id="1271071" ActName="Sadie Eden" CharName="Garindan (uncredited)"/>
			<Actor Id="1271072" ActName="Kim Falkinburg" CharName="Djas Puhr (uncredited)"/>
			<Actor Id="202402" ActName="Harry Fielder" CharName="Death Star Trooper (uncredited)"/>
			<Actor Id="1271073" ActName="Ted Gagliano" CharName="Stormtrooper with Binoculars (uncredited)"/>
			<Actor Id="1271074" ActName="Salo Gardner" CharName="Cantina Patron (uncredited)"/>
			<Actor Id="1195602" ActName="Steve Gawley" CharName="Death Star Trooper (uncredited)"/>
			<Actor Id="1271075" ActName="Barry Gnome" CharName="Kabe (uncredited)"/>
			<Actor Id="252527" ActName="Rusty Goffe" CharName="Kabe / Jawa / GONK Droid (uncredited)"/>
			<Actor Id="1271076" ActName="Isaac Grand" CharName="Cantina Patron (uncredited)"/>
			<Actor Id="1271077" ActName="Nelson Hall" CharName="Stormtrooper (special edition) (uncredited)"/>
			<Actor Id="1271078" ActName="Reg Harding" CharName="Stormtrooper (uncredited)"/>
			<Actor Id="964699" ActName="Alan Harris" CharName="Leia's Rebel Escort (uncredited)"/>
			<Actor Id="1271079" ActName="Frank Henson" CharName="Stormtrooper (uncredited)"/>
			<Actor Id="1271080" ActName="Christine Hewett" CharName="Brea Tonnika (uncredited)"/>
			<Actor Id="1271081" ActName="Arthur Howell" CharName="Stormtrooper (uncredited)"/>
			<Actor Id="1271082" ActName="Tommy Ilsley" CharName="Ponda Baba (uncredited)"/>
			<Actor Id="4945" ActName="Joe Johnston" CharName="Death Star Trooper (uncredited)"/>
			<Actor Id="1271083" ActName="Annette Jones" CharName="Mosep (uncredited)"/>
			<Actor Id="1148750" ActName="Linda Jones" CharName="Chall Bekan (uncredited)"/>
			<Actor Id="201344" ActName="Joe Kaye" CharName="Solomohal (uncredited)"/>
			<Actor Id="1271085" ActName="Colin Michael Kitchens" CharName="Stormtrooper (voice) (uncredited)"/>
			<Actor Id="1271086" ActName="Melissa Kurtz" CharName="Jawa (uncredited)"/>
			<Actor Id="1190780" ActName="Tiffany L. Kurtz" CharName="Jawa (uncredited)"/>
			<Actor Id="190453" ActName="Al Lampert" CharName="Daine Jir (uncredited)"/>
			<Actor Id="1012562" ActName="Anthony Lang" CharName="BoShek (uncredited)"/>
			<Actor Id="1271091" ActName="Laine Liska" CharName="Muftak / Cantina Band Member (uncredited)"/>
			<Actor Id="1271092" ActName="Derek Lyons" CharName="Temple Guard / Medal Bearer (uncredited)"/>
			<Actor Id="1271095" ActName="Mahjoub" CharName="Jawa (uncredited)"/>
			<Actor Id="1271096" ActName="Alf Mangan" CharName="Takeel (uncredited)"/>
			<Actor Id="19801" ActName="Rick McCallum" CharName="Stormtrooper (special edition) (uncredited)"/>
			<Actor Id="1271102" ActName="Grant McCune" CharName="Death Star Gunner (uncredited)"/>
			<Actor Id="1271104" ActName="Geoffrey Moon" CharName="Cantina Patron (uncredited)"/>
			<Actor Id="1271106" ActName="Mandy Morton" CharName="Swilla Corey (uncredited)"/>
			<Actor Id="1271107" ActName="Lorne Peterson" CharName="Massassi Base Rebel Scout (uncredited)"/>
			<Actor Id="1183443" ActName="Marcus Powell" CharName="Rycar Ryjerd (uncredited)"/>
			<Actor Id="10657" ActName="Shane Rimmer" CharName="InCom Engineer (uncredited)"/>
			<Actor Id="1271116" ActName="Pam Rose" CharName="Leesub Sirln (uncredited)"/>
			<Actor Id="110319" ActName="George Roubicek" CharName="Cmdr. Praji (Imperial Officer #2 on rebel ship) (uncredited)"/>
			<Actor Id="1271121" ActName="Erica Simmons" CharName="Tawss Khaa (uncredited)"/>
			<Actor Id="1271122" ActName="Angela Staines" CharName="Senni Tonnika (uncredited)"/>
			<Actor Id="1271123" ActName="George Stock" CharName="Cantina Patron (uncredited)"/>
			<Actor Id="1271124" ActName="Roy Straite" CharName="Cantina Patron (uncredited)"/>
			<Actor Id="1271125" ActName="Peter Sturgeon" CharName="Sai'torr Kal Fas (uncredited)"/>
			<Actor Id="187398" ActName="Peter Sumner" CharName="Lt. Pol Treidum (uncredited)"/>
			<Actor Id="1271126" ActName="John Sylla" CharName="Cantina Voices (voice) (uncredited)"/>
			<Actor Id="390158" ActName="Tom Sylla" CharName="Massassi Outpost Announcer / Various Voices (voice) (uncredited)"/>
			<Actor Id="166258" ActName="Malcolm Tierney" CharName="Lt. Shann Childsen (uncredited)"/>
			<Actor Id="7727" ActName="Phil Tippett" CharName="Cantina Alien (uncredited)"/>
			<Actor Id="184980" ActName="Burnell Tucker" CharName="Del Goren (uncredited)"/>
			<Actor Id="160947" ActName="Morgan Upton" CharName="Stormtrooper (voice) (uncredited)"/>
			<Actor Id="161301" ActName="Jerry Walter" CharName="Stormtrooper (voice) (uncredited)"/>
			<Actor Id="1271127" ActName="Hal Wamsley" CharName="Jawa (uncredited)"/>
			<Actor Id="159108" ActName="Larry Ward" CharName="Greedo (voice) (uncredited)"/>
			<Actor Id="1271128" ActName="Diana Sadley Way" CharName="Thuku (uncredited)"/>
			<Actor Id="1271129" ActName="Harold Weed" CharName="Ketwol / Melas (uncredited)"/>
			<Actor Id="24278" ActName="Bill Weston" CharName="Stormtrooper (uncredited)"/>
			<Actor Id="60207" ActName="Steve 'Spaz' Williams" CharName="Mos Eisley Citizen (special edition) (uncredited)"/>
			<Actor Id="1271131" ActName="Fred Wood" CharName="Cantina Patron (uncredited)"/>
			<Actor Id="301657" ActName="Colin Higgins" CharName="Rebel Pilot, Col. Takbright (uncredited)"/>
			<Actor Id="1490615" ActName="Ron Tarr" CharName="Jabba's Henchman (uncredited)"/>
		</Actors>
	</Film>
	<Film Id="12" PosterPath="/syPWyeeqzTQIxjIUaIFI7d0TyEY.jpg" >
		<Title OriginalTitle="Finding Nemo" >Finding Nemo</Title>
		<Time Day="30" Month="5" Year="2003"/>
		<Status>Released</Status>
		<Vote Count="9406">7.7</Vote>
		<RunTime>100</RunTime>
		<Certification>G</Certification>
		<Budget>9.4e+07</Budget>
		<Tag>There are 3.7 trillion fish in the ocean. They're looking for one.</Tag>
		<Genres>
			<Genre Id="16" Label="Animation"/>
			<Genre Id="10751" Label="Family"/>
		</Genres>
		<Directors>
			<Director Id="7" Name="Andrew Stanton"/>
		</Directors>
		<Actors>
			<Actor Id="13" ActName="Albert Brooks" CharName="Marlin (voice)"/>
			<Actor Id="14" ActName="Ellen DeGeneres" CharName="Dory (voice)"/>
			<Actor Id="12" ActName="Alexander Gould" CharName="Nemo (voice)"/>
			<Actor Id="5293" ActName="Willem Dafoe" CharName="Gill (voice)"/>
			<Actor Id="18" ActName="Brad Garrett" CharName="Bloat (voice)"/>
			<Actor Id="19" ActName="Allison Janney" CharName="Peach (voice)"/>
			<Actor Id="17401" ActName="Stephen Root" CharName="Bubbles (voice)"/>
			<Actor Id="6168" ActName="Austin Pendleton" CharName="Gurgle (voice)"/>
			<Actor Id="14723" ActName="Vicki Lewis" CharName="Deb / Flo (voice)"/>
			<Actor Id="7911" ActName="Joe Ranft" CharName="Jacques (voice)"/>
			<Actor Id="118" ActName="Geoffrey Rush" CharName="Nigel (voice)"/>
			<Actor Id="7" ActName="Andrew Stanton" CharName="Crush (voice)"/>
			<Actor Id="20" ActName="Elizabeth Perkins" CharName="Coral (voice)"/>
			<Actor Id="981048" ActName="Nicholas Bird" CharName="Squirt (voice)"/>
			<Actor Id="10" ActName="Bob Peterson" CharName="Mr. Ray (voice)"/>
			<Actor Id="22" ActName="Barry Humphries" CharName="Bruce (voice)"/>
			<Actor Id="8783" ActName="Eric Bana" CharName="Anchor (voice)"/>
			<Actor Id="27752" ActName="Bruce Spence" CharName="Chum (voice)"/>
			<Actor Id="23" ActName="Bill Hunter" CharName="Dentist (voice)"/>
			<Actor Id="981049" ActName="LuLu Ebeling" CharName="Darla (voice)"/>
			<Actor Id="1211731" ActName="Jordan Ranft" CharName="Tad (voice)"/>
			<Actor Id="1372790" ActName="Erica Beck" CharName="Pearl (voice)"/>
			<Actor Id="17190" ActName="Erik Per Sullivan" CharName="Sheldon (voice)"/>
			<Actor Id="7907" ActName="John Ratzenberger" CharName="Fish School (voice)"/>
			<Actor Id="84493" ActName="Mickie McGowan" CharName="Additional Voices (voice)"/>
			<Actor Id="19545" ActName="Jack Angel" CharName="Additional Voices (voice)"/>
		</Actors>
	</Film>
	<Film Id="13" PosterPath="/yE5d3BUhE8hCnkMUJOo1QDoOGNz.jpg" >
		<Title OriginalTitle="Forrest Gump" >Forrest Gump</Title>
		<Time Day="6" Month="7" Year="1994"/>
		<Status>Released</Status>
		<Vote Count="11871">8.4</Vote>
		<RunTime>142</RunTime>
		<Certification>PG-13</Certification>
		<Budget>5.5e+07</Budget>
		<Tag>Life is like a box of chocolates...you never know what you're gonna get.</Tag>
		<Genres>
			<Genre Id="35" Label="Comedy"/>
			<Genre Id="18" Label="Drama"/>
			<Genre Id="10749" Label="Romance"/>
		</Genres>
		<Directors>
			<Director Id="24" Name="Robert Zemeckis"/>
		</Directors>
		<Actors>
			<Actor Id="31" ActName="Tom Hanks" CharName="Forrest Gump"/>
			<Actor Id="32" ActName="Robin Wright" CharName="Jenny Curran"/>
			<Actor Id="33" ActName="Gary Sinise" CharName="Lt. Dan Taylor"/>
			<Actor Id="34" ActName="Mykelti Williamson" CharName="Pvt. Benjamin Buford 'Bubba' Blue"/>
			<Actor Id="35" ActName="Sally Field" CharName="Mrs. Gump"/>
			<Actor Id="37821" ActName="Michael Conner Humphreys" CharName="Young Forrest Gump"/>
			<Actor Id="204997" ActName="Hanna Hall" CharName="Young Jenny Curran"/>
			<Actor Id="9640" ActName="Haley Joel Osment" CharName="Forrest Gump Jr."/>
			<Actor Id="6751" ActName="Siobhan Fallon Hogan" CharName="School Bus Driver"/>
			<Actor Id="37825" ActName="Afemo Omilami" CharName="Drill Sergeant"/>
			<Actor Id="37822" ActName="Peter Dobson" CharName="Young Elvis Presley"/>
			<Actor Id="37823" ActName="Sonny Shroyer" CharName="College Football Coach"/>
			<Actor Id="951881" ActName="George Kelly" CharName="Barber"/>
			<Actor Id="36221" ActName="Sam Anderson" CharName="Principal"/>
			<Actor Id="1215432" ActName="Margo Moorer" CharName="Louise"/>
			<Actor Id="1019727" ActName="Christopher Jones" CharName="Boy with cross"/>
			<Actor Id="37832" ActName="Kevin Mangan" CharName="Jenny's Father"/>
			<Actor Id="29934" ActName="Brett Rice" CharName="High School Football Coach"/>
			<Actor Id="14526" ActName="Daniel C. Striepeke" CharName="Recruiter"/>
			<Actor Id="6310" ActName="David Brisbin" CharName="Newscaster"/>
			<Actor Id="154697" ActName="Kirk Ward" CharName="Earl"/>
			<Actor Id="37831" ActName="Marlena Smalls" CharName="Bubba's Mother"/>
			<Actor Id="37830" ActName="Kitty K. Green" CharName="Bubba's Great Grandmother"/>
			<Actor Id="975108" ActName="Mark Matheisen" CharName="Jenny's date"/>
			<Actor Id="129725" ActName="Al Harrington" CharName="Local Anchor #1"/>
			<Actor Id="37824" ActName="Jed Gillin" CharName="President Kennedy (voice)"/>
			<Actor Id="1346510" ActName="Don Fischer" CharName="Army Recruiter"/>
			<Actor Id="1088274" ActName="Matt Wallace" CharName="Barracks Recruit"/>
			<Actor Id="114326" ActName="Mike Jolly" CharName="Club patron"/>
			<Actor Id="170051" ActName="Michael Kemmerling" CharName="Club patron"/>
			<Actor Id="95140" ActName="John Voldstad" CharName="Club patron"/>
			<Actor Id="1446990" ActName="Daniel J. Gillooly" CharName="Helicopter gunman"/>
			<Actor Id="1401994" ActName="Michael Burgess" CharName="Cleveland"/>
			<Actor Id="1235787" ActName="Steven Griffith" CharName="Tex"/>
			<Actor Id="163441" ActName="Michael McFall" CharName="Army Hospital Male Nurse"/>
			<Actor Id="163441" ActName="Michael McFall" CharName="Wounded soldier"/>
			<Actor Id="92658" ActName="Byron Minns" CharName="Wounded soldier"/>
			<Actor Id="81692" ActName="Stephen Bridgewater" CharName="Hospital Officer"/>
			<Actor Id="37827" ActName="John William Galt" CharName="President Johnson (voice)"/>
			<Actor Id="1313819" ActName="Isabel Rose" CharName="Isabel"/>
			<Actor Id="1409948" ActName="Richard D'Alessandro" CharName="Abbie Hoffman"/>
			<Actor Id="46921" ActName="Michael Jace" CharName="Black Panther"/>
			<Actor Id="148122" ActName="Geoffrey Blake" CharName="Wesley"/>
			<Actor Id="406976" ActName="Vanessa Roth" CharName="Hollywood Boulevard Girlfriend"/>
			<Actor Id="10565" ActName="Dick Cavett" CharName="Dick Cavett"/>
			<Actor Id="1405338" ActName="Tiffany Salerno" CharName="Carla"/>
			<Actor Id="1405338" ActName="Tiffany Salerno" CharName="Lenore"/>
			<Actor Id="86434" ActName="Joe Alaskey" CharName="President Nixon (voice)"/>
			<Actor Id="1465241" ActName="Lazarus Jackson" CharName="Discharge Officer"/>
			<Actor Id="1465241" ActName="Lazarus Jackson" CharName="Drugged Out Boyfriend"/>
			<Actor Id="37828" ActName="Nora Dunfee" CharName="Elderly Southern Woman"/>
			<Actor Id="1327149" ActName="Hallie D'Amore" CharName="Waitress in cafe"/>
			<Actor Id="37829" ActName="Michael Mattison" CharName="Taxi Driver"/>
			<Actor Id="176329" ActName="Charles Boswell" CharName="Aging Hippie"/>
			<Actor Id="169643" ActName="Timothy McNeil" CharName="Wild eyed man"/>
			<Actor Id="196855" ActName="Bob Penny" CharName="Crony"/>
			<Actor Id="98873" ActName="Greg Brown" CharName="Football Player (uncredited)"/>
			<Actor Id="13204" ActName="Troy Christian" CharName="Cheerleader (uncredited)"/>
			<Actor Id="84901" ActName="Bryan Hanna" CharName="Football Coach (uncredited)"/>
			<Actor Id="1392671" ActName="Zach Hanner" CharName="Barracks Recruit (uncredited)"/>
			<Actor Id="1273540" ActName="Aaron Michael Lacey" CharName="National Guardsman (uncredited)"/>
			<Actor Id="42961" ActName="Jacqueline Lovell" CharName="Football Fan (uncredited)"/>
			<Actor Id="1150593" ActName="Brendan Shanahan" CharName="Football Player (uncredited)"/>
			<Actor Id="567126" ActName="William Shipman" CharName="Black Panther (uncredited)"/>
			<Actor Id="173277" ActName="Robb Skyler" CharName="Nicholas Katzenbach (uncredited)"/>
			<Actor Id="23967" ActName="Mary Ellen Trainor" CharName="Jenny's Babysitter (uncredited)"/>
			<Actor Id="6856" ActName="Kurt Russell" CharName="Elvis Presley (Voice)"/>
		</Actors>
	</Film>
	<Film Id="14" PosterPath="/3UBQGKS8c1dxRnDiu5kUK6ej3pP.jpg" >
		<Title OriginalTitle="American Beauty" >American Beauty</Title>
		<Time Day="15" Month="9" Year="1999"/>
		<Status>Released</Status>
		<Vote Count="5247">8</Vote>
		<RunTime>122</RunTime>
		<Certification>R</Certification>
		<Budget>1.5e+07</Budget>
		<Tag>Look closer.</Tag>
		<Genres>
			<Genre Id="18" Label="Drama"/>
		</Genres>
		<Directors>
			<Director Id="39" Name="Sam Mendes"/>
		</Directors>
		<Actors>
			<Actor Id="1979" ActName="Kevin Spacey" CharName="Lester Burnham"/>
			<Actor Id="516" ActName="Annette Bening" CharName="Carolyn Burnham"/>
			<Actor Id="2155" ActName="Thora Birch" CharName="Jane Burnham"/>
			<Actor Id="8210" ActName="Wes Bentley" CharName="Ricky Fitts"/>
			<Actor Id="8211" ActName="Mena Suvari" CharName="Angela Hayes"/>
			<Actor Id="2955" ActName="Chris Cooper" CharName="Colonel Frank Fitts"/>
			<Actor Id="19" ActName="Allison Janney" CharName="Barbara Fitts"/>
			<Actor Id="8212" ActName="Peter Gallagher" CharName="Buddy Kane"/>
			<Actor Id="2154" ActName="Scott Bakula" CharName="Jim Olmeyer"/>
			<Actor Id="8213" ActName="Sam Robards" CharName="Jim Berkley"/>
			<Actor Id="8214" ActName="Barry Del Sherman" CharName="Brad Dupree"/>
			<Actor Id="68842" ActName="John Cho" CharName="Sale House Man #1"/>
			<Actor Id="1658382" ActName="Hal Fort Atkinson" CharName="Sale House Man #2"/>
			<Actor Id="9634" ActName="Kent Faulcon" CharName="Sale House Man #3"/>
			<Actor Id="64189" ActName="Ara Celi" CharName="Sale House Woman #1"/>
			<Actor Id="166961" ActName="Sue Casey" CharName="Sale House Woman #2"/>
			<Actor Id="1397945" ActName="Brenda Wehle" CharName="Sale House Woman #3"/>
			<Actor Id="152796" ActName="Lisa Cloud" CharName="Sale House Woman #4"/>
			<Actor Id="42715" ActName="Amber Smith" CharName="Christy Kane"/>
			<Actor Id="12223" ActName="Joel McCrary" CharName="Catering Boss"/>
			<Actor Id="76742" ActName="Marissa Jaret Winokur" CharName="Mr. Smiley's Counter Girl (Janine)"/>
			<Actor Id="1441804" ActName="Dennis Anderson" CharName="Mr. Smiley's Manager"/>
			<Actor Id="177623" ActName="Matthew Kimbrough" CharName="Firing Range Attendant"/>
			<Actor Id="1448568" ActName="Erin Cathryn Strubbe" CharName="Young Jane"/>
			<Actor Id="101687" ActName="Alison Faulk" CharName="Spartanette #1"/>
			<Actor Id="1503019" ActName="Krista Goodsitt" CharName="Spartanette #2"/>
			<Actor Id="1503020" ActName="Lily Houtkin" CharName="Spartanette #3"/>
			<Actor Id="1503021" ActName="Carolina Lancaster" CharName="Spartanette #4"/>
			<Actor Id="1503022" ActName="Mona Leah" CharName="Spartanette #5"/>
			<Actor Id="1503023" ActName="Chekesha Van Putten" CharName="Spartanette #6"/>
			<Actor Id="1503024" ActName="Emily Zachary" CharName="Spartanette #7"/>
			<Actor Id="1503030" ActName="Nancy Anderson" CharName="Spartanette #8"/>
			<Actor Id="568656" ActName="Reshma Gajjar" CharName="Spartanette #9"/>
			<Actor Id="1503025" ActName="Stephanie Rizzo" CharName="Spartanette #10"/>
			<Actor Id="1503026" ActName="Heather Joy Sher" CharName="Playground Girl #1"/>
			<Actor Id="1219143" ActName="Chelsea Hertford" CharName="Playground Girl #2"/>
			<Actor Id="1503027" ActName="Elaine Corral Kendall" CharName="Newscaster (uncredited)"/>
			<Actor Id="1503028" ActName="David C. Fisher" CharName="Wedding Guest (uncredited)"/>
			<Actor Id="1503029" ActName="Tom Miller" CharName="Advertising Executive (uncredited)"/>
			<Actor Id="8215" ActName="Bruce Cohen" CharName="Bartender (uncredited)"/>
		</Actors>
	</Film>